server:
    port: 8083

# naming the application
spring:
    application:
        name: rabbitmq-publisher      # used as the id in the gateway routes

# configure where the discovery client is so our app can auto-register itself
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

    # configuring how long between each "heartbeat" request
    instance:
        leaseRenewalIntervalInSeconds: 30

# creating the rabbitmq fanout exchange
exchange:
    fanout: payment

# creating the routing key for the exchange
routing-key: key1234
