server:
    port: 8081

# naming the application
spring:
    application:
        name: accounts-service      # used as the id in the gateway routes

# configure where the discovery client is so our app can auto-register itself
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
