# Tell Spring where to get the data from
spring:
    datasource:
        #url: jdbc:h2:mem:moviesdb       # name of your db - if you want to peresits data between runs you can specify a file path: jdbc:h2:file:[path]
        #username: sa                    # this is the default username for h2
        #password:                       # optional for h2
        #driverClassName: org.h2.Driver  # jdbc uses this to connect to database

        #postgres
        #url: jdbc:postgresql://localhost:5432/movies
        #username: postgres
        #password:                                    # enter your own password
        
        #postgres with Aurora
        url: jdbc:postgresql://cahumada-db-instance-1.c4eqo06kg56i.us-east-1.rds.amazonaws.com:5432/movies
        username: postgres
        password: password123  


    #jpa:
        #database-platform: org.hibernate.dialect.H2Dialect      # tells spring data jpa that we're using h2 database
        #defer-datasource-initialization: true                   # tells JPA to wait until hibernate has initialized before loading the data to h2

    output:
        ansi:
            enabled: ALWAYS

#server:
    #port: 8282     # changes port number for server

# sets your logging level - default INFO
logging:
    level:
        com:
            skillstorm: debug
