server:
    port: 8125      # standard port for API Gateway

# setup the eureka client for the service discovery
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka   # location of eureka server

spring:
    cloud:
        gateway:
            cors-configurations:
                '[/**]':                                    # applying cors configuration to all routes
                    allowedOrigins: http://localhost:5176   # the places that are allowed to send requests to the gateway
                    allowedMethods:                         # list of all the allowed HTTP methods
                        - GET                               # yml list syntax
                        - POST
                        - PUT
                        - DELETE
            # defining where to route traffic to from the gateway 
            routes:
                # each service is going to need its own route configuration
                - id: accounts-service          # needs to match the spring.application.name in the services
                  uri: lb://accounts-service    # this can be any path - we'll use spring's own load balancer to manage traffic to accounts-service
                  predicates:                   # this path will map to this specific service
                    - Path=/accounts/**
                  filters:
                    - name: CircuitBreaker      # needs to be exactly this - it is referencing the CircuitBreaker class from Resilience4J
                      args:
                        name: fallBackController    # need to be in the format of a bean
                        # this fallback URI can be anywhere - another service entirely or stay on the gateway 
                        fallbackUri: forward:/cache/accounts    # forwarding the request to a different endpoint

                # each service is going to need its own route configuration
                - id: payments-service          # needs to match the spring.application.name in the services
                  uri: lb://payments-service    # this can be any path - we'll use spring's own load balancer to manage traffic to payments-service
                  predicates:                   # this path will map to this specific service
                    - Path=/payments/**

                - id: rabbitmq-publisher
                  uri: lb://rabbitmq-publisher
                  predicates:                   # this path will map to this specific service
                    - Path=/publisher/**



