apiVersion: v1
kind: Service
metadata:       
  name: my-nginx-service
spec:    
  type: LoadBalancer # ClusterIP (deafult), NodePort, ExternalName, LoadBalancer
  selector:  
    app: nginx
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80