server:
    port: 8084

# naming the application
spring:
    application:
        name: rabbitmq-subscriber      # used as the id in the gateway routes

# configure where the discovery client is so our app can auto-register itself
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

    # configuring how long between each "heartbeat" request
    instance:
        leaseRenewalIntervalInSeconds: 30

# creating the rabbitmq fanout exchange
exchanges:
    fanout: payment

# creating the queue for rabbitmq to read from
queues:
    fanout: paymentQueue

# creating the routing key for the exchange
routing-key: key1234
